// <auto-generated />
#pragma warning disable
#nullable enable

using System.Text.RegularExpressions;

namespace Alba.Framework.Text;

public static partial class MatchExts
{
    extension(Match @this)
    {
        public (string, string) Get(int g0, int g1) =>
            (@this.Get(g0), @this.Get(g1));

        public (string, string, string) Get(int g0, int g1, int g2) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2));

        public (string, string, string, string) Get(int g0, int g1, int g2, int g3) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3));

        public (string, string, string, string, string) Get(int g0, int g1, int g2, int g3, int g4) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4));

        public (string, string, string, string, string, string) Get(int g0, int g1, int g2, int g3, int g4, int g5) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5));

        public (string, string, string, string, string, string, string) Get(int g0, int g1, int g2, int g3, int g4, int g5, int g6) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5), @this.Get(g6));

        public (string, string, string, string, string, string, string, string) Get(int g0, int g1, int g2, int g3, int g4, int g5, int g6, int g7) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5), @this.Get(g6), @this.Get(g7));

        public (string, string) Get(string g0, string g1) =>
            (@this.Get(g0), @this.Get(g1));

        public (string, string, string) Get(string g0, string g1, string g2) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2));

        public (string, string, string, string) Get(string g0, string g1, string g2, string g3) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3));

        public (string, string, string, string, string) Get(string g0, string g1, string g2, string g3, string g4) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4));

        public (string, string, string, string, string, string) Get(string g0, string g1, string g2, string g3, string g4, string g5) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5));

        public (string, string, string, string, string, string, string) Get(string g0, string g1, string g2, string g3, string g4, string g5, string g6) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5), @this.Get(g6));

        public (string, string, string, string, string, string, string, string) Get(string g0, string g1, string g2, string g3, string g4, string g5, string g6, string g7) =>
            (@this.Get(g0), @this.Get(g1), @this.Get(g2), @this.Get(g3), @this.Get(g4), @this.Get(g5), @this.Get(g6), @this.Get(g7));

        public (IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1) =>
            (@this.GetAll(g0), @this.GetAll(g1));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2, int g3) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2, int g3, int g4) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2, int g3, int g4, int g5) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2, int g3, int g4, int g5, int g6) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5), @this.GetAll(g6));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(int g0, int g1, int g2, int g3, int g4, int g5, int g6, int g7) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5), @this.GetAll(g6), @this.GetAll(g7));

        public (IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1) =>
            (@this.GetAll(g0), @this.GetAll(g1));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2, string g3) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2, string g3, string g4) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2, string g3, string g4, string g5) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2, string g3, string g4, string g5, string g6) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5), @this.GetAll(g6));

        public (IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>, IEnumerable<string>) GetAll(string g0, string g1, string g2, string g3, string g4, string g5, string g6, string g7) =>
            (@this.GetAll(g0), @this.GetAll(g1), @this.GetAll(g2), @this.GetAll(g3), @this.GetAll(g4), @this.GetAll(g5), @this.GetAll(g6), @this.GetAll(g7));

        public (string?, string?) TryGet(int g0, int g1) =>
            (@this.TryGet(g0), @this.TryGet(g1));

        public (string?, string?, string?) TryGet(int g0, int g1, int g2) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2));

        public (string?, string?, string?, string?) TryGet(int g0, int g1, int g2, int g3) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3));

        public (string?, string?, string?, string?, string?) TryGet(int g0, int g1, int g2, int g3, int g4) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4));

        public (string?, string?, string?, string?, string?, string?) TryGet(int g0, int g1, int g2, int g3, int g4, int g5) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5));

        public (string?, string?, string?, string?, string?, string?, string?) TryGet(int g0, int g1, int g2, int g3, int g4, int g5, int g6) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5), @this.TryGet(g6));

        public (string?, string?, string?, string?, string?, string?, string?, string?) TryGet(int g0, int g1, int g2, int g3, int g4, int g5, int g6, int g7) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5), @this.TryGet(g6), @this.TryGet(g7));

        public (string?, string?) TryGet(string g0, string g1) =>
            (@this.TryGet(g0), @this.TryGet(g1));

        public (string?, string?, string?) TryGet(string g0, string g1, string g2) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2));

        public (string?, string?, string?, string?) TryGet(string g0, string g1, string g2, string g3) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3));

        public (string?, string?, string?, string?, string?) TryGet(string g0, string g1, string g2, string g3, string g4) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4));

        public (string?, string?, string?, string?, string?, string?) TryGet(string g0, string g1, string g2, string g3, string g4, string g5) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5));

        public (string?, string?, string?, string?, string?, string?, string?) TryGet(string g0, string g1, string g2, string g3, string g4, string g5, string g6) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5), @this.TryGet(g6));

        public (string?, string?, string?, string?, string?, string?, string?, string?) TryGet(string g0, string g1, string g2, string g3, string g4, string g5, string g6, string g7) =>
            (@this.TryGet(g0), @this.TryGet(g1), @this.TryGet(g2), @this.TryGet(g3), @this.TryGet(g4), @this.TryGet(g5), @this.TryGet(g6), @this.TryGet(g7));

    }
}
