// <auto-generated />
#pragma warning disable
#nullable enable

namespace Alba.Framework.Text;

public static partial class StringExts
{
    private const StringComparison CmpOrd = StringComparison.Ordinal;
    private const StringComparison CmpOrdCase = StringComparison.OrdinalIgnoreCase;
    private const StringComparison CmpInv = StringComparison.InvariantCulture;
    private const StringComparison CmpInvCase = StringComparison.InvariantCultureIgnoreCase;
    private const StringComparison CmpCur = StringComparison.CurrentCulture;
    private const StringComparison CmpCurCase = StringComparison.CurrentCultureIgnoreCase;

    extension(string @this)
    {
        [Pure] public bool EqualsOrd(string other) => @this.Equals(other, CmpOrd);
        [Pure] public bool ContainsOrd(string value) => @this.Contains(value, CmpOrd);
        [Pure] public bool StartsWithOrd(string value) => @this.StartsWith(value, CmpOrd);
        [Pure] public bool EndWithOrd(string value) => @this.EndsWith(value, CmpOrd);
        [Pure] public int IndexOfOrd(string value) => @this.IndexOf(value, CmpOrd);
        [Pure] public int IndexOfOrd(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpOrd);
        [Pure] public int IndexOfOrd(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpOrd);
        [Pure] public int IndexOfOrd(char value) => @this.IndexOf(value, CmpOrd);
        [Pure] public int LastIndexOfOrd(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpOrd);
        [Pure] public int LastIndexOfOrd(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpOrd);
        [Pure] public string ReplaceOrd(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpOrd);

        [Pure] public bool EqualsOrdCase(string other) => @this.Equals(other, CmpOrdCase);
        [Pure] public bool ContainsOrdCase(string value) => @this.Contains(value, CmpOrdCase);
        [Pure] public bool StartsWithOrdCase(string value) => @this.StartsWith(value, CmpOrdCase);
        [Pure] public bool EndWithOrdCase(string value) => @this.EndsWith(value, CmpOrdCase);
        [Pure] public int IndexOfOrdCase(string value) => @this.IndexOf(value, CmpOrdCase);
        [Pure] public int IndexOfOrdCase(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpOrdCase);
        [Pure] public int IndexOfOrdCase(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpOrdCase);
        [Pure] public int IndexOfOrdCase(char value) => @this.IndexOf(value, CmpOrdCase);
        [Pure] public int LastIndexOfOrdCase(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpOrdCase);
        [Pure] public int LastIndexOfOrdCase(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpOrdCase);
        [Pure] public string ReplaceOrdCase(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpOrdCase);

        [Pure] public bool EqualsInv(string other) => @this.Equals(other, CmpInv);
        [Pure] public bool ContainsInv(string value) => @this.Contains(value, CmpInv);
        [Pure] public bool StartsWithInv(string value) => @this.StartsWith(value, CmpInv);
        [Pure] public bool EndWithInv(string value) => @this.EndsWith(value, CmpInv);
        [Pure] public int IndexOfInv(string value) => @this.IndexOf(value, CmpInv);
        [Pure] public int IndexOfInv(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpInv);
        [Pure] public int IndexOfInv(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpInv);
        [Pure] public int IndexOfInv(char value) => @this.IndexOf(value, CmpInv);
        [Pure] public int LastIndexOfInv(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpInv);
        [Pure] public int LastIndexOfInv(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpInv);
        [Pure] public string ReplaceInv(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpInv);

        [Pure] public bool EqualsInvCase(string other) => @this.Equals(other, CmpInvCase);
        [Pure] public bool ContainsInvCase(string value) => @this.Contains(value, CmpInvCase);
        [Pure] public bool StartsWithInvCase(string value) => @this.StartsWith(value, CmpInvCase);
        [Pure] public bool EndWithInvCase(string value) => @this.EndsWith(value, CmpInvCase);
        [Pure] public int IndexOfInvCase(string value) => @this.IndexOf(value, CmpInvCase);
        [Pure] public int IndexOfInvCase(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpInvCase);
        [Pure] public int IndexOfInvCase(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpInvCase);
        [Pure] public int IndexOfInvCase(char value) => @this.IndexOf(value, CmpInvCase);
        [Pure] public int LastIndexOfInvCase(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpInvCase);
        [Pure] public int LastIndexOfInvCase(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpInvCase);
        [Pure] public string ReplaceInvCase(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpInvCase);

        [Pure] public bool EqualsCur(string other) => @this.Equals(other, CmpCur);
        [Pure] public bool ContainsCur(string value) => @this.Contains(value, CmpCur);
        [Pure] public bool StartsWithCur(string value) => @this.StartsWith(value, CmpCur);
        [Pure] public bool EndWithCur(string value) => @this.EndsWith(value, CmpCur);
        [Pure] public int IndexOfCur(string value) => @this.IndexOf(value, CmpCur);
        [Pure] public int IndexOfCur(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpCur);
        [Pure] public int IndexOfCur(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpCur);
        [Pure] public int IndexOfCur(char value) => @this.IndexOf(value, CmpCur);
        [Pure] public int LastIndexOfCur(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpCur);
        [Pure] public int LastIndexOfCur(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpCur);
        [Pure] public string ReplaceCur(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpCur);

        [Pure] public bool EqualsCurCase(string other) => @this.Equals(other, CmpCurCase);
        [Pure] public bool ContainsCurCase(string value) => @this.Contains(value, CmpCurCase);
        [Pure] public bool StartsWithCurCase(string value) => @this.StartsWith(value, CmpCurCase);
        [Pure] public bool EndWithCurCase(string value) => @this.EndsWith(value, CmpCurCase);
        [Pure] public int IndexOfCurCase(string value) => @this.IndexOf(value, CmpCurCase);
        [Pure] public int IndexOfCurCase(string value, int startIndex) => @this.IndexOf(value, startIndex, CmpCurCase);
        [Pure] public int IndexOfCurCase(string value, int startIndex, int count) => @this.IndexOf(value, startIndex, count, CmpCurCase);
        [Pure] public int IndexOfCurCase(char value) => @this.IndexOf(value, CmpCurCase);
        [Pure] public int LastIndexOfCurCase(string value, int startIndex) => @this.LastIndexOf(value, startIndex, CmpCurCase);
        [Pure] public int LastIndexOfCurCase(string value, int startIndex, int count) => @this.LastIndexOf(value, startIndex, count, CmpCurCase);
        [Pure] public string ReplaceCurCase(string oldValue, string? newValue) => @this.Replace(oldValue, newValue, CmpCurCase);

    }
}
